#!/usr/bin/env python

import os
import sys
import importlib

if 'kernel' not in os.environ:
    print "cannot find kernel path in environ"
    exit(0)
    
kernel_path = os.environ['kernel']
sys.path.append(kernel_path)

from df.datamodel.schema import SCHEMA
from df.datamodel.schema import DATATYPE
import df.data_function as data_function
from df.data_descriptor import DataDesc
from core.cache import Cache_Service
    
detail_schema_name = "schema_Basic_Media_model"
detail_data_type = "get_detail_page_model"

welcome = (
    '''  +------------------------------------------------------------\n'''
    '''   BULK CACHE DELETION FOR THE MEDIA DETAIL PAGE\n'''
    '''   \n'''
    '''   all the media detail page cache will be delete by on action\n'''
    '''  ------------------------------------------------------------+\n''')

if __name__ == "__main__":
    print welcome

    if not hasattr(SCHEMA, detail_schema_name):
        print "no %s schema found"%detail_schema_name
        exit(0)
    if not hasattr(DATATYPE, detail_data_type):
        print "no %s datatype found"%detail_data_type
        exit(0)

    
    cache_key = data_function.make_hcached_key(SCHEMA.schema_Basic_Media_model,
                                               DATATYPE.get_detail_page_model)

    s = "schema={0}({1}) | datatype={2}({3})".\
        format("schema_Basic_Media_model", SCHEMA.schema_Basic_Media_model,
               "get_detail_page_model", DATATYPE.get_detail_page_model)

    print "Below all detail page be DELETED in cache system: "
    print s
    print "-" * len(s)
    confirm = raw_input("confirm (y/n): ")
    if confirm.lower() != 'y':
        print "++ Bulk Cache Deletion for detail page task CANCELED !!"
        exit(0)

    cache = Cache_Service()
    cache.delete(cache_key)
    
    print "++ Bulk Cache for detail page has been cleaned successfully"

    
