#!/usr/bin/env python

import os
import sys
import importlib

if 'kernel' not in os.environ:
    print "cannot find kernel path in environ"
    exit(0)
    
kernel_path = os.environ['kernel']
sys.path.append(kernel_path)

from df.datamodel.schema import SCHEMA
from df.datamodel.schema import DATATYPE
import df.data_function as data_function
from df.data_descriptor import DataDesc
from core.cache import Cache_Service
    
category_schema_name = "schema_search"
category_data_types = ["data_type_query_pinyin_cache",
                       "data_type_query_pinyin",
                       "data_type_query_all",
                       "data_type_query_t9_cache",
                       "data_type_query_t9"
                       ]


welcome = (
    '''  +-------------------------------------------------------------------\n'''
    '''   BULK CACHE DELETION FOR THE Category Media list\n'''
    '''   There are several type of categories need to be cleaned one by one\n'''
    '''  -------------------------------------------------------------------+\n''')

def delete_one_data_type(dtstr):
    dt = getattr(DATATYPE, dtstr)
    s = "schema={0}({1}) | datatype={2}({3})".\
        format("schema_search", SCHEMA.schema_search,
               dtstr, dt)
    print "Below category information be DELETED in cache system: "
    #print "-" * len(s)
    print s
    print "-" * len(s)
    confirm = raw_input("confirm (y/n/q(quit)): ")
    if confirm.lower() == 'y':
        pass
    elif confirm.lower() == 'q':
        print "++ Bulk Cache Deletion for category media list task QUIT"
        exit(0)
    else:
        print "++ Bulk Cache Deletion for category media list task CANCELED !!\n"
        return
    cache = Cache_Service()
    cachekey = data_function.make_hcached_key(SCHEMA.schema_search, dt)
    print "++ cache deletion for schema %s, datatype %s succeed\n"\
          %("schema_search", dtstr)


if __name__ == "__main__":
    print welcome

    if not hasattr(SCHEMA, category_schema_name):
        print "no %s schema found"%detail_schema_name
        exit(0)
    for data_type in  category_data_types:
        if not hasattr(DATATYPE, data_type):
            print "no %s datatype found"%data_type
            exit(0)
        delete_one_data_type(data_type)
    
    print "++ Bulk Cache for category media list has been cleaned successfully"

    
