#!/usr/bin/env python

all_callback = [
    {"type_code": 1001, "title": "category", "call": "/category/api/search", "params": "/{0}",
     "activity": "com.hisense.vod.activity.MovieActivity"},
    {"type_code": 1002, "title": "movie", "call": "/medias/api/media", "params": "/{0}",
     "activity": "com.hisense.vod.activity.SetDetailActivity"},
    {"type_code": 1003, "title": "tvserial", "call": "/medias/api/media", "params": "/{0}",
     "activity": "com.hisense.vod.activity.SetDetailActivity"},
    {"type_code": 1004, "title": "application", "call": "/medias/api/media", "params": "/{0}", "activity": ""},
    {"type_code": 1005, "title": "feature", "call": "/frontpage/api/feature_views", "params":"", "activity": ""},
    {"type_code": 2001, "title": "search", "call": "/medias/api/topMediaFromSearch", "params": "",
     "activity": "com.hisense.vod.activity.SearchActivity"},
    {"type_code": 2002, "title": "all_watching", "call": "/stat/api/allwatching", "params": "",
     "activity": "com.hisense.vod.activity.EveryoneLookActivity"},
    {"type_code": 2003, "title": "new_for_7_days", "call": "/medias/api/new7days", "params": "",
     "activity": "com.hisense.vod.activity.SevendayRefreshActivity"},
    {"type_code": 2004, "title": "hot_list", "call": "/recom/api/getPopularBoard", "params": "",
     "activity": "com.hisense.vod.activity.HotListActivity"},
    {"type_code": 2005, "title": "topic", "call": "/medias/api/topic/detailpage", "params": "/{0}",
     "activity": "com.hisense.vod.activity.SpecficTopic"},
    {"type_code": 2006, "title": "guess_your_like", "call": "/recom/api/getGuess", "params": "/{0}",
     "activity": "com.hisense.vod.activity.GussYouLikeActivity"},
    {"type_code": 2007, "title": "related_medias", "call": "/recom/api/getRelatedMedia", "params": "?media={0}",
     "activity": ""},
    {"type_code": 2008, "title": "topic_list", "call": "/medias/api/topic/topiclist", "params": "", "activity": ""},
    {"type_code": 2009, "title": "search_result", "call": "/search/api/getResult", "params": "", "activity": ""},
    {"type_code": 3001, "title": "history", "call": "usercenter/api/getMedias", "params": "", "activity": ""},
    {"type_code": 3002, "title": "catch", "call": "usercenter/api/getMedias", "params": "", "activity": ""},
    {"type_code": 3003, "title": "favorite", "call": "usercenter/api/getMedias", "params": "", "activity": ""},
    {"type_code": 3004, "title": "add_favorite", "call": "/usercenter/api/collect/add", "params": "", "activity": ""},
    {"type_code": 3005, "title": "del_favorite", "call": "/usercenter/api/collect/delete", "params": "", "activity": ""},
    {"type_code": 3006, "title": "get_usercenter_info", "call": "/usercenter/api/getIndexInfo", "params": "", "activity": ""},
    {"type_code": 3007, "title": "check_update", "call": "/upgrade/api/checkUpdate", "params": "", "activity": ""},
    {"type_code": 3008, "title": "log_report", "call": "/", "params": "", "activity": ""},
    {"type_code": 3009, "title": "history_upload", "call": "/usercenter/api/history/add", "params": "", "activity": ""}
]
