#!/usr/bin/env python

import os
import sys
import importlib

if 'kernel' not in os.environ:
    print "cannot find kernel path in environ"
    exit(0)
    
kernel_path = os.environ['kernel']
sys.path.append(kernel_path)

#schema = importlib.import_module('df.datamodel.schema')
#
#if not hasattr(schema, "SCHEMA"):
#    print "schema module has no SCHEMA attribute"
#    exit(0)
#
#if not hasattr(schema, "DATATYPE"):
#    print "schema module has no DATATYPE attribute"
#    exit(0)

#SCHEMA = getattr(schema, "SCHEMA")
#DATATYPE = getattr(schema, "DATATYPE")
from df.datamodel.schema import SCHEMA
from df.datamodel.schema import DATATYPE
import df.data_function as data_function
from df.data_descriptor import DataDesc
    
detail_schema_name = "schema_Basic_Media_model"
detail_data_type = "get_detail_page_model"

welcome = (
    '''  +-------------------------------------------\n'''
    '''   CACHE DELETION FOR THE MEDIA DETAIL PAGE\n'''
    '''  -------------------------------------------+\n''')

if __name__ == "__main__":
    print welcome
    mid = raw_input("clean the media detail page, enter the media id: ")
    print
    
    if not hasattr(SCHEMA, detail_schema_name):
        print "no %s schema found"%detail_schema_name
        exit(0)
    if not hasattr(DATATYPE, detail_data_type):
        print "no %s datatype found"%detail_data_type
        exit(0)

    data_desc = DataDesc(SCHEMA.schema_Basic_Media_model,
                         DATATYPE.get_detail_page_model)
    data_desc.setKey(1, mid)

    s = "schema={0} | datatype={1} | mediaId={2} | cacheKey={3}".\
        format(data_desc.schema, data_desc.data_type, mid,
               data_function.make_hcached_key(
                   data_desc.schema, data_desc.data_type))

    print "below information will be DELETED in cache system: "
    print "-" * len(s)
    print s
    print "-" * len(s)
    confirm = raw_input("confirm (y/n): ")
    if confirm.lower() != 'y':
        print "++ Cache deletion for detail page [ %s ] task CANCELED !!"%mid
        exit(0)
    
    
    data_function.db_flush_cache(data_desc)

    print "++ Cache for detail page [ %s ] has been cleaned successfully"%mid

    
